spring.application.name=TinyTrail

# TinyTrail - tiny links, big path.

spring.datasource.url=jdbc:mysql://localhost:3306/tinytrail
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt_expiration=86400000
jwt_secret=your-super-secret-jwt-key

ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000

logging.level.org.springframework.security=DEBUG